### ISSUE TITLE
5. As a user, I want to join an existing shopping list so I can share a shopping list with another person. 

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/smart-shopping-list#8]
## Summary
We want to allow users to join existing shopping lists so they can manage them with friends or family. This would take the following steps:
1. User enters an existing token into a form
2. The token is saved to `localStorage`
3. The user is taken to the `List` view and shown the existing list.

## Acceptance criteria
If a user **doesn’t** already have a token:
- [ ] The `Home` view shows a form that allows the user to enter a token to join an _existing_ list, in addition to the button that allows them to create a _new_ list.
- [ ] The input that accepts the list token has a semantic `label` element associated with its
- [ ] The user can submit this form with both the mouse and the `Enter` key
- [ ] If the list exists,
	- the token is saved in `localStorage`
	- the user is redirected to the `List` view and shown the items on that list
- [ ] If the list _does not_ exist, the user is shown an error message that explains the problem

If a user **does** already have a token:
- [ ] They are automatically redirected to the `List` view.

## Notes
- Be sure to use the `setListToken` function to save the token that the user enters!
- You will know your `<label>` is correctly implemented if you click on the label and keyboard focus moves to the related input. Refer to [the MDN docs on `<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) for more info.
- Users will be able to submit the form with the `Enter` key if you listen for the right JavaScript event on the right element! If you're adding an `onKeyDown` listener anywhere, you might be overcomplicating things.
- You can assume that users will only be sharing a token if the list has actual items on it. So, let's say I create a New Shopping List, but never add any items to it, and haven't saved that particular token to Firestore, we can assume that's a list that doesn't exist.
- If you would like, you can save the token to Firestore immediately when creating a list, and then a user would be able to share an empty list (see issue 3).

**Comment by lindseyindev** [comment]
Draft 1 for review: need more details on the setListToken hook bc I think they'll need to send 2 arguments into setListToken but the second arg is the local storage key which can probably be set in the template and not be dynamic so  collabies only have to send 1 argument in which is the actual token



Tokens can be shared with other users to allow them to co-manage a given list.

Joining an existing list consists of the following:

* User enters an existing token into an input field
* Save the token to `localStorage` via the `setListToken` custom hook

AC:

* When the user does not already have a token in `localStorage`, on the onboarding/home screen, a simple form is displayed that allows the user to enter a token
* Entering the shared token and hitting submit saves the token to a user's `localStorage` and sets the token as the `listToken` state variable used by the useEffect hook to get list data from firebase
* On submit, create error handling if the token does not exist in firebase. Firebase sends an error message if you attempt to reference a collection that does not exist but we need to catch and display this error to users.
* If they get an error message, allow them to try again or create a new list
Notes:
* As of this story, the welcome/home screen will be feature complete, as reflected in this wireframe: https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/welcome-screen.png
* For accessibility reasons, use a `<label>` tag for the "share token" field.
* If a user creates a token and doesn't add any items to that token, the token will only exist in local storage on their browser, not in Firestore. Firestore doesn't accept empty collections so with our app the token is only saved in Firestore when the user adds their first item(s). You can assume that users will only be sharing a token if the list has at least 1 item added to it.
* If you would like, you can save the token to Firestore immediately when creating a list, and then a user would be able to share an empty list (see issue 5).

**Comment by jeremiahfallin** [comment]
Curriculum revamp edit:

## Title

5. As a user, I want to be able to invite others to an existing shopping list.

## Summary

We want to allow users to invite others to existing shopping lists so they can manage them with friends or family. This would take the following steps:

1. User enters an existing user's email into a form
2. The `shareList` function in `src/api/firebase.js` is called with the appropriate inputs

## Acceptance criteria

- [ ]  The `ManageList` view shows a form that allows the user to enter an email to invite an _existing_ user to a list, in addition to the form that allows them to add items to that list.
- [ ]  The input that accepts the email  has a semantic `label` element associated with it
- [ ]  The user can submit this form with both the mouse and the `Enter` key
- [ ]  If the other user exists, the user is alerted that the list was shared
- [ ]  If the other user _does not_ exist, the user is shown an error message that explains the problem

## Notes

- You will know your `<label>` is correctly implemented if you click on the label and keyboard focus moves to the related input. Refer to [the MDN docs on `<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) for more info.
- Users will be able to submit the form with the `Enter` key if you listen for the right JavaScript event on the right element! If you're adding an `onKeyDown` listener anywhere, you might be overcomplicating things.
